create table if not exists contacts (
  id          bigint generated by default as identity primary key,
  name        text,
  phone       text not null,
  raw         jsonb,
  status      text not null default 'pending',
  created_at  timestamptz not null default now()
);

create table if not exists responses (
  id            bigint generated by default as identity primary key,
  contact_id    bigint references contacts(id) on delete set null,
  name          text,
  phone         text,
  collected_enc text,
  created_at    timestamptz not null default now()
);

create index if not exists idx_contacts_status on contacts(status);
create index if not exists idx_responses_created on responses(created_at desc);
